super_hexagon:
  build: ./
  volumes:
    - ./share:/home/super_hexagon:ro
    - ./xinetd:/etc/xinetd.d/super_hexagon:ro
    - ./tmp:/tmp:rw
  ports:
    - "6666:6666"
  expose:
    - "6666"
  cap_add:
      - ALL
  security_opt:
      - seccomp:unconfined
